### ISSUE TITLE
Uploading to create albums w/existing photos

### ISSUE THREAD

**Issue by toyo44444** [ylexus/jiotty-photos-uploader#30]
Hi, I saw your Reddit post saying that uploading with existing photos was working. So I was using the app on Mac and I was trying to upload to get the app to create an album for me when I had previously uploaded the photos via web browser or backup and sync and for some reason I can't get it to create that album if the photos exist already. If the photos have not been uploaded before, the app works perfectly and does create that album. Any insight on how you were able to get that to work initially when you had existing photos? I also tried deleting the photos and then even permanently deleting and then re uploading through the app but then that didn't work either.

Thank you for your help!

**Comment by mwerther** [comment]
Also, I tested this and made sure there were no existing albums with the same name that the uploaded would have created as you had said to not do.

**Comment by ylexus** [comment]
@mwerther can I ask you to try this:
1. Delete everything from ~/jiottyphotosuploader/logs
2. Create a single folder A with a single sub-folder B and put a single photo into the folder B. Please choose the phot that was already uploaded by yourself or backup and sync. 
3. Run Jiotty and ask it it upload folder A

What is the outcome? Do you see any failures in the app? If yes, can you please attach screenshots?
Please attach the logs from ~/jiottyphotosuploader/logs. The logs will contain your username and the file name of your photos so if you want to mask those that’s fine.

**Comment by ylexus** [comment]
It definitely worked for me and for the other user, as you can see from this comment https://www.reddit.com/r/googlephotos/comments/ge2bpa/jiotty_photos_uploader_upload_your_collection/fpnd4jh/?utm_source=share&utm_medium=ios_app&utm_name=iossmf so there’s something interesting going on with your setup.

**Comment by mwerther** [comment]
@ylexus thank you for the help. I'm not technical but I think I can definitely handle what you are saying. Since I reached out to you I have been testing and I think in the way you are suggesting (folder A with sub-folder B and photos in sub-folder B it seems to work better). I also had just uploaded the files into google photos (and it was a couple thousand photos) and some were already in and some were brand new so I think that could have been tripping it up. I think also google takes a while to process those files on the backend so that could have been making it more complicated. I will keep testing in the way you are suggesting b/c I have many more files to upload and I will let you know if I catch any further issues. I'm just trying to recreate exactly where the issue occurs and I haven't figured that out yet but will keep trying and will keep you informed. As you were saying, I think that the issue is more likely to occur in this scenario: I have folder A with sub-folders B C D all with various images in the subfolders. I dragged folders B C D separately into the uploader and I think that's when it happens. I also had some issues where I ran out of original storage on google photos but that was later so I think that would obviously cause issues as well. 

Also, I just want to mention that the issue that this simple app solves is an extreme pain point and there are many people that have been searching for a solution for a long, long time. IMO you should market this to everyday non-technical people as well because I know there are many that would use it. I certainly would pay for this and I know many others would as well. As far as I am aware, there is only one competitor who has similar functionality out there who has a non-command line interface called PIcBackMan and they are charging an insane amount of money and the software is absolute trash. Your initial release of this app is light years faster and more stable than theirs. Let me know if I can help you in any other way. Thx.

**Comment by ylexus** [comment]
@toyo44444 thanks for your kind words. Please let me know if you are able to isolate this error scenario. 

I found indeed that there’s a gap on the market here. I tried to market the going through the first page of google results for “google photos upload folder album”. A lot of these are locked discussion streams or stack exchange sites that I don’t have enough Karma to post to. Wherever I could I posted, including reddit, quora, a self-answered question on Google Photos google groups, and I think a comment to one of the Stack Exchange questions. Where else do you think I should market?

As for paying for this. I don’t think I want to make it a paid app. I don’t want to be dealing with payment systems and it’s not really in the spirit of the app. There seems to be no way of publishing a java app to Microsoft Store at the moment (#15). There’s an optional donation link in the app, and so far I had two small donations! ;)

**Comment by ylexus** [comment]
Added a clarifying image to the folder selection screen to emphasise that you need to select the top level folder :)  <img width="612" alt="Screenshot 2020-05-16 at 22 42 18" src="https://user-images.githubusercontent.com/6009806/82130798-96f24500-97c6-11ea-80f1-6512f1c3e923.png">
