### ISSUE TITLE
1.4.0 Windows 10 install error

### ISSUE THREAD

**Issue by axylee** [ylexus/jiotty-photos-uploader#64]
1.4.0 install in Windows 10 fail 

![image](https://user-images.githubusercontent.com/65884869/88369449-a7c0c780-cdc2-11ea-968a-ec7c4b25e570.png)
![image](https://user-images.githubusercontent.com/65884869/88369480-b60ee380-cdc2-11ea-9cac-1964f00a9060.png)

**Comment by ylexus** [comment]
Seem like my code signing certificate issuer is having issues with their timestamping server. I've submitted a support ticket for them:

I am creating Windows MSIX packages signed with my sectigo/comodo certificate. Last time it worked well was 9 July 2020. Today (24 July 2020), when I create an MSIX package for the same application, it succeeds (no errors in the MSIX Packaging Tool logs), but the package fails on installation with this error:

error 0x80096005: Opening the package from location JiottyPhotosUploader_1.4.0.0_x64__6pc5kwsssk5nj.msix failed.

This error code means this:

0x80096005 TRUST_E_TIME_STAMP The timestamp signature and/or certificate could not be verified or is malformed.

I can see other people had been having the same issue with comodo timestamping server on 17 July 2020: https://techcommunity.microsoft.com/t5/msix-packaging-and-tools/microsoft-msix-packaging-tool-does-not-notice-timestamping-issue/m-p/1530069

I tried specifying http://timestamp.sectigo.com/rfc3161 as time stamping server instead of http://timestamp.comodoca.com, but it did not help. What should I do?

**Comment by ylexus** [comment]
I've removed the Windows 10 package from the release page - it's broken anyway.

**Comment by ylexus** [comment]
Indeed it's because of the timestamping server issues:

---
Thank you for contacting Sectigo Technical support. 

We are sorry for the delay in response.

Yes, there is a issue with the timestamp server and our team is investigating the issue. We will get back to you with an update at earliest.

Please let us know if you need any further support.

**Comment by ylexus** [comment]
Fixed in [1.4.1](https://github.com/ylexus/jiotty-photos-uploader/releases/tag/1.4.1)
