### ISSUE TITLE
Continuously monitor folders and automatically upload new files.

### ISSUE THREAD

**Issue by Cantolla** [ylexus/jiotty-photos-uploader#87]
Ability to monitor a file continuously/after X time/ etc, adding files to those folders will upload the files to the corresponding Album.

Alternatively be able to create an upload set, to avoid having to browse/choose the folder each time.

**Comment by ylexus** [comment]
Continuous monitoring would transform it to a sync app, while for now it's a simple uploader. It's also quite a lot of work to do it properly.

Avoiding to browse/choose folder each time is something I contemplated, as if you're doing many retries it's a little annoying. I could allow for creation a set of root to upload, then store them, so that they are still there every if you restart the app. Then there will be a separate Start button. This I may be able to do.

**Comment by Cantolla** [comment]
That would be a great solution, if you could select one or more folders that the uploader would remember, essentially creating a "backup set" that would make things much smoother/faster.
I'd greatly appreciate it.

**Comment by ylexus** [comment]
This is now done. Please don't close as I'll need some new translations. 

@marcovanree, @sngnr, could you please translate a small amount of  new phrases in `src/main/resources/i18n`? I've marked them with TODO. I've also invited your as collaborators to simplify the process - you do not need to use forks, just create branches right here and create pull requests from those branches to master. Thanks a lot!

**Comment by ylexus** [comment]
Released in https://github.com/ylexus/jiotty-photos-uploader/releases/tag/1.6.0. Feedback welcome. Translations pending.

**Comment by ylexus** [comment]
Released with translations in 1.6.1. @Cantolla does it work well for you?
